{% set version = "2.9.2" %}

package:
  name: rancher-cli
  version: {{ version }}

source:
  url: https://github.com/rancher/cli/archive/v{{ version }}.tar.gz
  sha256: 6da91cd58ad5c56d51a14a21ffc27201e46ad25c7fa91ecedad3230bc00fb085

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - {{ stdlib("c") }}
    - go-licenses

test:
  requires:
    - m2-grep  # [win]
  commands:
    - rancher --help
    - rancher --version
    - rancher --version | grep -iE "^rancher version v{{ version.replace(".", "\.") }}$"

about:
  home: https://github.com/rancher/cli
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  summary: The Rancher Command Line Interface (CLI) is a unified tool for interacting with your Rancher Server.
  doc_url: https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/rancher-cli

extra:
  recipe-maintainers:
    - bollwyvl
